// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCw0K-6a5AcMOyD1xVo5igm9BEUls08114',
    appId: '1:156389780519:web:b8618e4641ac766380f202',
    messagingSenderId: '156389780519',
    projectId: 'abp-database',
    authDomain: 'abp-database.firebaseapp.com',
    storageBucket: 'abp-database.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyApqGlUmpmtfgg1ngvLZadmnzokAhnBBaY',
    appId: '1:156389780519:android:42d0c04b7783de7580f202',
    messagingSenderId: '156389780519',
    projectId: 'abp-database',
    storageBucket: 'abp-database.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBIPXUpDDTsCmYD6881apFigxoeDF7xM44',
    appId: '1:156389780519:ios:56befc4936caac7c80f202',
    messagingSenderId: '156389780519',
    projectId: 'abp-database',
    storageBucket: 'abp-database.firebasestorage.app',
    iosBundleId: 'com.example.fitspaceSportsVenueBookingMobile',
  );

}